[pytest]
markers =
    ui: mark test as a UI test
    api: mark test as an API test
    smoke: mark test as a smoke test

addopts = --html=test-results/report.html --self-contained-html -v --tb=short
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*